name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, ubuntu-18.04, windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          yarn install

      - name: Run lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run lint

      - name: Publish release Mac
        if: matrix.os == 'macos-10.14'
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run release

      - name: Publish release Linux
        if: matrix.os == 'ubuntu-18.04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run release

      - name: Publish release Windows
        if: matrix.os == 'windows-2019'
        env:
          CSC_LINK: ${{ secrets.CSC_LINK_WINDOWS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run release

# Failing beacuse virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
