name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, ubuntu-18.04, windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish release Mac
        if: startsWith(matrix.os, 'mac')
        env:
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run release

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Publish release Linux
        if: startsWith(matrix.os, 'ubuntu')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Publish release Windows
        if: startsWith(matrix.os, 'win')
        env:
          CSC_LINK: ${{ secrets.CSC_LINK_WINDOWS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run release

# Failing beacuse virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
